## YAML Template.
---
- emoticon: ":)"
  image: smile.png
  title: Smile
- emoticon: ':('
  image: sad.png
  title: Sad
- emoticon: ':P'
  image: tongue.png
  title: Tongue
- emoticon: ':D'
  image: biggrin.png
  title: Big grin
- emoticon: ';)'
  image: wink.png
  title: Wink
- emoticon: '(/)'
  image: check.png
  title: Check
- emoticon: '(x)'
  image: x_mark.png
  title: X_mark
- emoticon: '(!)'
  image: warning.png
  title: Warning
